Repository naverStoreProject/naverStoreProjectFront, pull requests merged in 2025-05, with the labels that each got.

#25 FEAT: 헤더 구조 및 홈 기본 레이아웃 설정
  package-lock.json
  package.json
  src/components/layouts/AppLayout.vue
  src/components/layouts/Header.vue
  src/components/layouts/LoginBarBanner.vue
  src/components/layouts/MainShortcutBar.vue
  src/components/layouts/TabBar.vue
  src/components/layouts/header/Header.vue
  src/components/layouts/header/header.ts
  src/components/offCanvas/offCanvas.ts
  src/components/offCanvas/offCanvas.vue
  src/env.d.ts
  src/main.ts
  src/pages/home/HomePage.vue
  src/pages/home/_components/BestItem.vue
  src/pages/home/_components/CardNews.vue
  src/pages/home/_components/Delivery.vue
  src/pages/home/_components/FashionBeauty.vue
  src/pages/home/_components/ForYou.vue
  src/pages/home/_components/HomeMain.vue
  src/pages/home/_components/HomeNav.vue
  src/pages/home/_components/TodayDeal.vue
  src/pages/home/_components/TodaySale.vue
  src/pages/side/SuperCreditPoint.vue
  src/router/index.ts
  src/utils/route.ts
  tsconfig.app.json
Labels: ⚡️feature, 🎨design, ♻️refactor

#27 Memo /26/tailwind/0513
  .gitignore
  .prettierrc
  .vscode/settings.json
  package.json
  pnpm-lock.yaml
  rules/README.md
  src/App.vue
  src/assets/main.css
  src/components/buttons/Button.vue
  src/components/layouts/AppLayout.vue
  src/components/layouts/TabBar.vue
  src/components/products/ProductCard.vue
  src/components/products/ProductList.vue
  src/components/products/tmpProductData.ts
  src/pages/home/HomePage.vue
  src/pages/search/SearchPage.vue
  src/pages/user/MypageListPage.vue
Labels: 📝docs, 🎨design

#33 ⚡️/14/공통컴포넌트(0513)
  pnpm-lock.yaml
  src/assets/main.css
  src/assets/navBack.svg
  src/assets/navFront.svg
  src/components/buttons/BaseBtn.vue
  src/components/buttons/Button.stories.ts
  src/components/buttons/Button.vue
  src/components/buttons/NavBtn.vue
  src/components/icons/BaseIcon.vue
  src/components/icons/Icon.vue
  src/components/inputs/SelectBox.vue
  src/pages/home/HomePage.vue
  src/pages/notfound/Page404.vue
  src/stories/BaseBtn.stories.ts
  src/stories/BaseIcon.stories.ts
  src/stories/Icon.stories.ts
  src/stories/NavBtn.stories.ts
  src/stories/Select.stories.ts
Labels: ⚡️feature

#46 ⚡️: 마이페이지 메인 화면 레이아웃 작성
  src/components/icons/Icon.vue
  src/pages/user/MypageListPage.vue
  src/pages/user/MypagePage.vue
  src/pages/user/_components/.gitkeep
  src/pages/user/_components/IconsBox.vue
  src/pages/user/_components/ProductsBox.vue
Labels: ⚡️feature

#48 🎨: 탭바 디자인 수정
  src/assets/main.css
  src/components/buttons/BaseBtn.vue
  src/components/inputs/SelectBox.vue
  src/components/layouts/LoginBarBanner.vue
  src/components/layouts/TabBar.vue
  src/components/panels/searchInputPanel.vue
  src/components/panels/searchResultPanel.vue
  src/pages/category/_components/LeftNav.vue
  src/pages/category/_components/RightNav.vue
  src/pages/search/SearchPage.vue
Labels: 🎨design
