Repository naverStoreProject/naverStoreProjectFront, pull requests merged in 2025-06, with the labels that each got.

#53 ⚡️: 비활성화 및 페이지 이동 처리 완료
  index.html
  package.json
  pnpm-lock.yaml
  public/naver.png
  src/assets/image/icons/npayIcon.svg
  src/assets/image/icons/orderIcon.svg
  src/assets/image/icons/reviewIcon.svg
  src/assets/image/icons/userIcon.png
  src/assets/main.css
  src/pages/user/MypageListPage.vue
  src/pages/user/_components/IconsBox.vue
  src/pages/user/_components/ProductsBox.vue
  src/router/index.ts
Labels: ⚡️feature

#52 🩹: 디자인, 탭바이동 오류 수정
  src/App.vue
  src/assets/main.css
  src/components/icons/Icon.vue
  src/components/layouts/TabBar.vue
  src/components/panels/searchInputPanel.vue
  src/components/panels/searchResultPanel.vue
  src/pages/category/_components/LeftNav.vue
  src/pages/category/_components/RightNav.vue
  src/pages/home/HomePage.vue
  src/pages/notfound/Page404.vue
  src/pages/user/MypageListPage.vue
  src/pages/user/_components/ProductsBox.vue
Labels: 🚨bug

#55 ⚡️: 주문내역페이지 레이아웃 생성
  src/assets/image/icons/closeIcon.svg
  src/components/buttons/BaseBtn.vue
  src/pages/user/_components/OrderBox.vue
  src/pages/user/orders/OrderData.ts
  src/pages/user/orders/OrderListPage.vue
Labels: ⚡️feature

#58 🎨 : 오늘 끝딜 / ForYou / 오늘행사 레이아웃 틀 (40/home/0522) 브렌치에 PR 요청
  src/pages/home/_components/ForYou.vue
  src/pages/home/_components/ForYouCard.vue
  src/pages/home/_components/ForYouList.vue
  src/pages/home/_components/HomeInterest.vue
  src/pages/home/_components/HomeMain.vue
  src/pages/home/_components/HomeTodaySale.vue
  src/pages/home/_components/InterestCarousel.vue
  src/pages/home/_components/TodayDeal.vue
  src/pages/home/_components/TodayDeal/BrandDeal.vue
  src/pages/home/_components/TodayDeal/BrandDealCard.vue
  src/pages/home/_components/TodayDeal/LastDeal.vue
  src/pages/home/_components/TodayDeal/SpecialDeal.vue
  src/pages/home/_components/TodayDeal/SpecialDealCard.vue
  src/pages/home/_components/TodayDeal/TodayDeal.vue
  src/pages/home/_components/TodayDeal/TodayOnlyDeal.vue
  src/pages/home/_components/TodayDeal/TodayOnlyDealCard.vue
  src/pages/home/_components/TodaySale.vue
  src/pages/home/_components/TodaySaleCard.vue
  src/pages/home/_components/TodaySaleList.vue
  src/pages/home/forYouData.ts
  src/pages/home/todayDeal.ts
  src/pages/home/todaySaleData.ts
  src/router/index.ts
Labels: 🎨design
